# @generated by usage-cli from .usage.kdl
_mcp_scaffold() {
    if ! type -p usage &> /dev/null; then
        echo >&2
        echo "Error: usage CLI not found. This is required for completions to work in mcp-scaffold." >&2
        echo "See https://usage.jdx.dev for more information." >&2
        return 1
    fi

	local cur prev words cword was_split comp_args
    _comp_initialize -n : -- "$@" || return
    local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_mcp_scaffold.spec"
    cat >| "$spec_file" <<'__USAGE_EOF__'
name mcp-scaffold
bin mcp-scaffold
about "Programmable scaffolder + migrator for mcp-cli-starter-template"
flag "-v --verbose" help="Log debug-level info to stderr"
flag --yes help="Non-interactive: accept defaults for any unset value"
flag --no-banner help="Suppress the ascii banner"
cmd init help="Fresh scaffold into <target> (defaults to cwd)" {
    flag --name help="Tool name (kebab-case, BARE — no -mcp suffix)" {
        arg <name>
    }
    flag --scope help="Npm scope, with leading @" {
        arg <scope>
    }
    flag --package-manager help="pnpm | npm | bun (fresh scaffolds require pnpm; existing repos auto-detect)" {
        arg <pm> {
            choices pnpm npm bun
        }
    }
    flag --runtime-source help="source | registry (source remains default until the first public runtime release)" {
        arg <source> {
            choices source registry
        }
    }
    flag --no-tui help="Skip the Ink/React TUI surface"
    flag --no-http help="Skip the Streamable HTTP transport"
    flag --no-rust-accel help="Skip the optional Rust acceleration crate"
    flag --no-semantic-release help="Skip the semantic-release workflow"
    arg "[target]" help="Target directory (defaults to cwd)" required=#false
}
cmd apply help="Apply migrations to an existing repo" {
    flag --target help="Path to the existing repo" {
        arg <dir>
    }
    flag --execute help="Actually apply (default is dry-run)"
    flag --existing-strategy help="safe | full (default: safe; full opts generic repos into starter infrastructure)" {
        arg <strategy> {
            choices safe full
        }
    }
    flag --report-json help="Write a machine-readable migration report" {
        arg <path>
    }
    flag --force help="Overwrite files that diverge from the template (default: preserve user customizations)"
    flag --name help="Tool name (kebab-case, BARE — no -mcp suffix)" {
        arg <name>
    }
    flag --scope help="Npm scope, with leading @" {
        arg <scope>
    }
    flag --package-manager help="pnpm | npm | bun (fresh scaffolds require pnpm; existing repos auto-detect)" {
        arg <pm> {
            choices pnpm npm bun
        }
    }
    flag --runtime-source help="source | registry (source remains default until the first public runtime release)" {
        arg <source> {
            choices source registry
        }
    }
    flag --no-tui help="Skip the Ink/React TUI surface"
    flag --no-http help="Skip the Streamable HTTP transport"
    flag --no-rust-accel help="Skip the optional Rust acceleration crate"
    flag --no-semantic-release help="Skip the semantic-release workflow"
}
cmd plan help="Dry-run preview of which migrations would apply" {
    flag --target help="Path to target repo" {
        arg <dir>
    }
    flag --mode help="'new' or 'existing' (default: existing)" {
        arg <mode> {
            choices new existing
        }
    }
    flag --existing-strategy help="safe | full (default: safe; full opts generic repos into starter infrastructure)" {
        arg <strategy> {
            choices safe full
        }
    }
    flag --report-json help="Write a machine-readable migration report" {
        arg <path>
    }
    flag --name help="Tool name (kebab-case, BARE — no -mcp suffix)" {
        arg <name>
    }
    flag --scope help="Npm scope, with leading @" {
        arg <scope>
    }
    flag --package-manager help="pnpm | npm | bun (fresh scaffolds require pnpm; existing repos auto-detect)" {
        arg <pm> {
            choices pnpm npm bun
        }
    }
    flag --runtime-source help="source | registry (source remains default until the first public runtime release)" {
        arg <source> {
            choices source registry
        }
    }
    flag --no-tui help="Skip the Ink/React TUI surface"
    flag --no-http help="Skip the Streamable HTTP transport"
    flag --no-rust-accel help="Skip the optional Rust acceleration crate"
    flag --no-semantic-release help="Skip the semantic-release workflow"
}
cmd migrate help="Run a single migration or one whole phase" {
    flag --target help="Path to target repo" {
        arg <dir>
    }
    flag --mode help="'new' or 'existing' (default: existing)" {
        arg <mode> {
            choices new existing
        }
    }
    flag --execute help="Actually apply (default is dry-run)"
    flag --force help="Overwrite divergent files (default: preserve in existing mode)"
    flag --report-json help="Write a machine-readable migration report" {
        arg <path>
    }
    flag --name help="Tool name (kebab-case, BARE — no -mcp suffix)" {
        arg <name>
    }
    flag --scope help="Npm scope, with leading @" {
        arg <scope>
    }
    flag --package-manager help="pnpm | npm | bun (fresh scaffolds require pnpm; existing repos auto-detect)" {
        arg <pm> {
            choices pnpm npm bun
        }
    }
    flag --runtime-source help="source | registry (source remains default until the first public runtime release)" {
        arg <source> {
            choices source registry
        }
    }
    flag --no-tui help="Skip the Ink/React TUI surface"
    flag --no-http help="Skip the Streamable HTTP transport"
    flag --no-rust-accel help="Skip the optional Rust acceleration crate"
    flag --no-semantic-release help="Skip the semantic-release workflow"
    arg <id> help="e.g. 04-robustness/m1-robustness-pkg, or just 04-robustness"
}
cmd add-mcp-app help="Add a second MCP app to apps/<name>-mcp/ inside an existing scaffolded repo" {
    flag --target help="Path to the scaffolded repo" {
        arg <dir>
    }
    flag --scope help="Npm scope, with leading @. Auto-detected from existing apps/*-mcp/ if omitted." {
        arg <scope>
    }
    flag --runtime-source help="source | registry. Auto-detected from existing app dependencies if omitted." {
        arg <source> {
            choices source registry
        }
    }
    flag --no-tui help="Skip the Ink/React TUI surface for the new app"
    flag --no-http help="Skip the Streamable HTTP transport for the new app"
    flag --no-rust-accel help="Skip the rust-accel workspace dep for the new app"
    arg <name> help="Bare tool name for the new app (no -mcp suffix)"
}
cmd list help="List discovered phases + migrations"
__USAGE_EOF__
    # shellcheck disable=SC2207
	_comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
	_comp_ltrim_colon_completions "$cur"
    # shellcheck disable=SC2181
    if [[ $? -ne 0 ]]; then
        unset COMPREPLY
    fi
    return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
    shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _mcp_scaffold mcp-scaffold
else
    shopt -u hostcomplete && complete -o nospace -o bashdefault -F _mcp_scaffold mcp-scaffold
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
