# @generated by usage-cli from .usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in mcp-scaffold." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_mcp_scaffold 'name mcp-scaffold
bin mcp-scaffold
about "Programmable scaffolder + migrator for mcp-cli-starter-template"
flag "-v --verbose" help="Log debug-level info to stderr"
flag --yes help="Non-interactive: accept defaults for any unset value"
flag --no-banner help="Suppress the ascii banner"
cmd init help="Fresh scaffold into <target> (defaults to cwd)" {
    flag --name help="Tool name (kebab-case, BARE — no -mcp suffix)" {
        arg <name>
    }
    flag --scope help="Npm scope, with leading @" {
        arg <scope>
    }
    flag --package-manager help="pnpm | npm | bun (fresh scaffolds require pnpm; existing repos auto-detect)" {
        arg <pm> {
            choices pnpm npm bun
        }
    }
    flag --no-tui help="Skip the Ink/React TUI surface"
    flag --no-install help="Skip the package-manager install after dependencies change"
    flag --no-http help="Skip the Streamable HTTP transport"
    flag --no-rust-accel help="Skip the optional Rust acceleration crate"
    flag --no-semantic-release help="Skip the semantic-release workflow"
    flag --cli-bin help="Bin name for the standalone usage(1) artifacts pipeline (08-app/m2-cli-artifacts)" {
        arg <name>
    }
    flag --cli-dir help="Repo-relative directory receiving the usage(1) artifacts pipeline (default: .)" {
        arg <dir>
    }
    arg "[target]" help="Target directory (defaults to cwd)" required=#false
}
cmd apply help="Apply migrations to an existing repo" {
    flag --target help="Path to the existing repo" {
        arg <dir>
    }
    flag --execute help="Actually apply (default is dry-run)"
    flag --existing-strategy help="safe | full (default: safe; full opts generic repos into starter infrastructure)" {
        arg <strategy> {
            choices safe full
        }
    }
    flag --report-json help="Write a machine-readable migration report" {
        arg <path>
    }
    flag --force help="Overwrite files that diverge from the template (default: preserve user customizations)"
    flag --name help="Tool name (kebab-case, BARE — no -mcp suffix)" {
        arg <name>
    }
    flag --scope help="Npm scope, with leading @" {
        arg <scope>
    }
    flag --package-manager help="pnpm | npm | bun (fresh scaffolds require pnpm; existing repos auto-detect)" {
        arg <pm> {
            choices pnpm npm bun
        }
    }
    flag --no-tui help="Skip the Ink/React TUI surface"
    flag --no-install help="Skip the package-manager install after dependencies change"
    flag --no-http help="Skip the Streamable HTTP transport"
    flag --no-rust-accel help="Skip the optional Rust acceleration crate"
    flag --no-semantic-release help="Skip the semantic-release workflow"
    flag --cli-bin help="Bin name for the standalone usage(1) artifacts pipeline (08-app/m2-cli-artifacts)" {
        arg <name>
    }
    flag --cli-dir help="Repo-relative directory receiving the usage(1) artifacts pipeline (default: .)" {
        arg <dir>
    }
}
cmd plan help="Dry-run preview of which migrations would apply" {
    flag --target help="Path to target repo" {
        arg <dir>
    }
    flag --mode help="\'new\' or \'existing\' (default: existing)" {
        arg <mode> {
            choices new existing
        }
    }
    flag --existing-strategy help="safe | full (default: safe; full opts generic repos into starter infrastructure)" {
        arg <strategy> {
            choices safe full
        }
    }
    flag --report-json help="Write a machine-readable migration report" {
        arg <path>
    }
    flag --name help="Tool name (kebab-case, BARE — no -mcp suffix)" {
        arg <name>
    }
    flag --scope help="Npm scope, with leading @" {
        arg <scope>
    }
    flag --package-manager help="pnpm | npm | bun (fresh scaffolds require pnpm; existing repos auto-detect)" {
        arg <pm> {
            choices pnpm npm bun
        }
    }
    flag --no-tui help="Skip the Ink/React TUI surface"
    flag --no-install help="Skip the package-manager install after dependencies change"
    flag --no-http help="Skip the Streamable HTTP transport"
    flag --no-rust-accel help="Skip the optional Rust acceleration crate"
    flag --no-semantic-release help="Skip the semantic-release workflow"
    flag --cli-bin help="Bin name for the standalone usage(1) artifacts pipeline (08-app/m2-cli-artifacts)" {
        arg <name>
    }
    flag --cli-dir help="Repo-relative directory receiving the usage(1) artifacts pipeline (default: .)" {
        arg <dir>
    }
}
cmd migrate help="Run a single migration or one whole phase" {
    flag --target help="Path to target repo" {
        arg <dir>
    }
    flag --mode help="\'new\' or \'existing\' (default: existing)" {
        arg <mode> {
            choices new existing
        }
    }
    flag --execute help="Actually apply (default is dry-run)"
    flag --force help="Overwrite divergent files (default: preserve in existing mode)"
    flag --report-json help="Write a machine-readable migration report" {
        arg <path>
    }
    flag --name help="Tool name (kebab-case, BARE — no -mcp suffix)" {
        arg <name>
    }
    flag --scope help="Npm scope, with leading @" {
        arg <scope>
    }
    flag --package-manager help="pnpm | npm | bun (fresh scaffolds require pnpm; existing repos auto-detect)" {
        arg <pm> {
            choices pnpm npm bun
        }
    }
    flag --no-tui help="Skip the Ink/React TUI surface"
    flag --no-install help="Skip the package-manager install after dependencies change"
    flag --no-http help="Skip the Streamable HTTP transport"
    flag --no-rust-accel help="Skip the optional Rust acceleration crate"
    flag --no-semantic-release help="Skip the semantic-release workflow"
    flag --cli-bin help="Bin name for the standalone usage(1) artifacts pipeline (08-app/m2-cli-artifacts)" {
        arg <name>
    }
    flag --cli-dir help="Repo-relative directory receiving the usage(1) artifacts pipeline (default: .)" {
        arg <dir>
    }
    arg <id> help="e.g. 07-shared-types/m1-shared-types, or just 07-shared-types"
}
cmd add-mcp-app help="Add a second MCP app to apps/<name>-mcp/ inside an existing scaffolded repo" {
    flag --target help="Path to the scaffolded repo" {
        arg <dir>
    }
    flag --scope help="Npm scope, with leading @. Auto-detected from existing apps/*-mcp/ if omitted." {
        arg <scope>
    }
    flag --no-tui help="Skip the Ink/React TUI surface for the new app"
    flag --no-install help="Skip the package-manager install after dependencies change"
    flag --no-http help="Skip the Streamable HTTP transport for the new app"
    flag --no-rust-accel help="Skip the rust-accel workspace dep for the new app"
    arg <name> help="Bare tool name for the new app (no -mcp suffix)"
}
cmd list help="List discovered phases + migrations"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_mcp_scaffold.spec"
echo $_usage_spec_mcp_scaffold > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc mcp-scaffold -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc mcp-scaffold -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
