/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Plain hello-world for integration tests. */
export declare function hello(name: string): string

/**
 * Demo Rust path for the `noop` MCP tool. Echoes the input string,
 * optionally upper-cased, and reports the wall-clock duration in
 * microseconds.
 */
export declare function noopAccel(input: NoopInput): NoopOutput

export interface NoopInput {
  input: string
  upper: boolean
}

export interface NoopOutput {
  echo: string
  /** Either "ts" or "rust"; the Rust path always returns "rust". */
  engine: string
  durationMicros: number
}
