# @generated by usage-cli from .usage.kdl
_example_repo() {
    if ! type -p usage &> /dev/null; then
        echo >&2
        echo "Error: usage CLI not found. This is required for completions to work in example-repo." >&2
        echo "See https://usage.jdx.dev for more information." >&2
        return 1
    fi

	local cur prev words cword was_split comp_args
    _comp_initialize -n : -- "$@" || return
    local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_example_repo.spec"
    cat >| "$spec_file" <<'__USAGE_EOF__'
name example-repo
bin example-repo
about "example-repo — MCP server + CLI + TUI (single bin, subcommand dispatch)"
flag --json help="Emit machine-readable JSON output"
flag "-q --quiet" help="Suppress non-error output"
flag "-v --verbose" help="Log debug-level info to stderr"
flag --no-color help="Disable colors"
cmd mcp help="Run the MCP server (stdio default; --http for Streamable HTTP)" {
    flag --http help="Use Streamable HTTP transport (requires MCP_HTTP_TOKEN)"
    flag --port help="HTTP port (default 8080)" {
        arg <port>
    }
    flag --bind help="HTTP bind addr (default 127.0.0.1)" {
        arg <host>
    }
}
cmd tui help="Launch the Ink TUI"
cmd doctor help="Run preflight checks (Node version, native module, config dir)"
cmd repl help="Interactive REPL driving the in-process dispatcher" {
    alias console
}
cmd health help="Print server health snapshot (calls health_check in-process)"
cmd noop help="Demo: call the noop tool" {
    flag --input help="Input string to echo" required=#true {
        arg <text>
    }
    flag --upper help="Return upper-cased"
}
__USAGE_EOF__
    # shellcheck disable=SC2207
	_comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
	_comp_ltrim_colon_completions "$cur"
    # shellcheck disable=SC2181
    if [[ $? -ne 0 ]]; then
        unset COMPREPLY
    fi
    return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
    shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _example_repo example-repo
else
    shopt -u hostcomplete && complete -o nospace -o bashdefault -F _example_repo example-repo
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
