# @generated by usage-cli from .usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in example-repo." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_example_repo 'name example-repo
bin example-repo
about "example-repo — MCP server + CLI + TUI (single bin, subcommand dispatch)"
flag --json help="Emit machine-readable JSON output"
flag "-q --quiet" help="Suppress non-error output"
flag "-v --verbose" help="Log debug-level info to stderr"
flag --no-color help="Disable colors"
cmd mcp help="Run the MCP server (stdio default; --http for Streamable HTTP)" {
    flag --http help="Use Streamable HTTP transport (requires MCP_HTTP_TOKEN)"
    flag --port help="HTTP port (default 8080)" {
        arg <port>
    }
    flag --bind help="HTTP bind addr (default 127.0.0.1)" {
        arg <host>
    }
}
cmd tui help="Launch the Ink TUI"
cmd doctor help="Run preflight checks (Node version, native module, config dir)"
cmd repl help="Interactive REPL driving the in-process dispatcher" {
    alias console
}
cmd health help="Print server health snapshot (calls health_check in-process)"
cmd noop help="Demo: call the noop tool" {
    flag --input help="Input string to echo" required=#true {
        arg <text>
    }
    flag --upper help="Return upper-cased"
}
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_example_repo.spec"
echo $_usage_spec_example_repo > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc example-repo -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc example-repo -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
